// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ioptwnsczckjxstzsynj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvcHR3bnNjemNranhzdHpzeW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1Njg2NzQsImV4cCI6MjA3ODE0NDY3NH0.Coa3IYmhhz4TuqwSr9Zp-4GfH7JOufqCOTbI5ylBGsA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);